# Generated by Django 2.2.7 on 2019-11-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
